from userbot import bot as raider
from userbot.utils import admin_cmd as choot

x = True
@raider.on(choot(pattern="nhire"))
async def d3vilraid(event):
    while x != False:
       
        await event.delete()
        kek = event.chat_id
        await raider.send_message(kek, "HACKERPROS KI MA RANDI") 
        await raider.send_message(kek, " ADITYA JAYESH KI MAA RANDI HAI SASTI WALI 💥❌🍆😂😂 ")
        await raider.send_message(kek, "ADI BETA TERIIIIII MAA RANDI💥💥🔥💦💦💦💦🍌💦  ")
        await raider.send_message(kek, "ADI KI MAAA KIIII CHOOTT MAARUU 💦💦🍑💦🍑💦🍑")
        await raider.send_message(kek, "ADI TERI MAA SASTI RANDI🍆🍌🍆🍌🍌🍌")
        await raider.send_message(kek, " ADI TU MADERRCHODD HAI 💦🔥👅👅💦💦💦💦 ")
        await raider.send_message(kek, "TERI  BEHENN KEE GAND ME  LODEEE 🍑🍆🍌🍌🍌")
        await raider.send_message(kek, "SHAFIQUE KI MAA KI CHOOTT KAAT DUNGAA🍆😂💦💦❌❌")
        await raider.send_message(kek, "RANDI KAA PILAA ADI AAJA TERI MAA KA CHOTT XHOD DU🍆😂🍆😂❌❌💦👅🔥🔥🍑🍑🍑")
        await raider.send_message(kek, "MADEERCHODD  ADIIII   ")
        await raider.send_message(kek, "KAALAAP GYII  TERIII MAAAA🍆🍌👅👅🍌💥💦 ")
        await raider.send_message(kek, "TERII MAAA KI CHOOT PHAAR DIYA HU 💥💥💥💦❌💦🍆💦🍆💦💦💦" )
        await raider.send_message(kek, "ADIII BETAA TERE 💦🍆🍌🍌")
        await raider.send_message(kek, "KHANDAANN KO")
        await raider.send_message(kek, "ANDARRRR TKK ")
        await raider.send_message(kek, "CHOD DALAAA")
        await raider.send_message(kek, "ADI TERIIII")
        await raider.send_message(kek, "BEHENNN")
        await raider.send_message(kek, "ABHII MERE LAUDE PE HAI 🍑🍑💥🍑💦🍆🍌🍌")
        await raider.send_message(kek, "ADITYA JAYESH KI MAA MERE LUND PE ")
        await raider.send_message(kek, "BETAA TERI MAA CHUDD RHI HAIII ")
        await raider.send_message(kek, "ADITYA JAYESH KI MAA CHUD GYI")
        await raider.send_message(kek, "ADITYA JAYESH KI MAAA SASTI RANDI HAI ")
        await raider.send_message(kek, "ADITYA JAYESH KI MAA KE CHUTT MEE")
        await raider.send_message(kek, "HATHII KAA")
        await raider.send_message(kek, "LAUDAA")
        await raider.send_message(kek, "GHUSAA DIYAA")
        await raider.send_message(kek, "MADEERRCHODDD TERI MAA.  KI GAND.  KAAT LUNGAA")
        await raider.send_message(kek, "ADITYA JAYESH. KI.  MAA. RANDII ")
        await raider.send_message(kek, "ADITYA JAYESH ")
        await raider.send_message(kek, "RANDI KAA PILLAAA HAI ")
        await raider.send_message(kek, "BEHENCHODDD")
        await raider.send_message(kek, "TERIII")
        await raider.send_message(kek, "BEHENN RANDI HAI SASTI WALIB🍑❌🍑🍑❌🍌💦🍌💦🍌💦")
        await raider.send_message(kek, " ADI BETA KI MAA KI ")
        await raider.send_message(kek, "CHUTTT ")
        await raider.send_message(kek, "MEEE")
        await raider.send_message(kek, "TOWERRR")
        await raider.send_message(kek, "GHUSAA DIYAA")
        await raider.send_message(kek, "ADITYA JAYESH KI. BEHAN KI CHOOTTT.  MERE.  LUND PE HAI SMJHAA🍌🍌🍆🍆")
        await raider.send_message(kek, "BETA ADITYA JAYESH TERI MAA KA RAPE KRR DALA HU")
        await raider.send_message(kek, "SUNO GUYS MAI ADITYA JAYESH KAA BAAAP HU. 💥🔥💥🔥🔥")
        await raider.send_message(kek, "ABE MADHARCHOD ADITYA JAYESH 🍌🍆🍑💦👅👅💦💦💦")
        await raider.send_message(kek, "ADITYA JAYESH  TUM JAAO. APNI MAA KE GANDD ME 💦🍌😂🍌👅👅👅")
        await raider.send_message(kek, "ADITYA JAYESH KI MAA AUR BEHAN KI GAND CHOODD DALA AND USKO MARR DALA")
        await raider.send_message(kek, "ADITYA JAYESH  MADHARCHOD HAI ")
        await raider.send_message(kek, "ADITYA JAYESH KI. ")
        await raider.send_message(kek, "ZINDAGIIII")
        await raider.send_message(kek, "ANDHERIII")
        await raider.send_message(kek, "KARRRR")
        await raider.send_message(kek, "DUGAAA")
        await raider.send_message(kek, "MADERRRCHODDD")
        await raider.send_message(kek, "BEHENNN")
        await raider.send_message(kek, "KEEE")
        await raider.send_message(kek, "LODEEE")
        await raider.send_message(kek, "AISAAA")
        await raider.send_message(kek, "CHODUGAAA")
        await raider.send_message(kek, "BSDKKK")
        await raider.send_message(kek, "PHIRRR")
        await raider.send_message(kek, "SEEE")
        await raider.send_message(kek, "KISIII")
        await raider.send_message(kek, "SEEE GANDD")
        await raider.send_message(kek, " MARANEE")
        await raider.send_message(kek, "KEE")
        await raider.send_message(kek, "LAYAKKK")
        await raider.send_message(kek, "NAHII BACHEGAAA")
        await raider.send_message(kek, "BAAAP")
        await raider.send_message(kek, "SEEE")
        await raider.send_message(kek, "PANGAA")
        await raider.send_message(kek, "LIYA HAIII")
        await raider.send_message(kek, "BSDKK TUU")
        await raider.send_message(kek, "ANDARRR TAK")
        await raider.send_message(kek, "CHUDEGGAAA")
        await raider.send_message(kek, "TERIII")
        await raider.send_message(kek, "MAAAA")
        await raider.send_message(kek, "KAAA RAPEE")
        await raider.send_message(kek, "KARR DIYAA")
        await raider.send_message(kek, "MADERRCHODDD")
        await raider.send_message(kek, "BEHENCHODD")
        await raider.send_message(kek, "TERAAA")
        await raider.send_message(kek, "ASLIII")
        await raider.send_message(kek, "BAAAP MAINN")
        await raider.send_message(kek, "HI HUINNN")
        await raider.send_message(kek, "BSDKK")
        await raider.send_message(kek, "TERI MAA")
        await raider.send_message(kek, "KOO KOTHEE")
        await raider.send_message(kek, "PE CHODAA")
        await raider.send_message(kek, "THAA GHODII BANAKEE")
        await raider.send_message(kek, "JAKEEE")
        await raider.send_message(kek, "PUCHHH APNI")
        await raider.send_message(kek, "APNI")
        await raider.send_message(kek, "SAMJHAA LAWDE")
        await raider.send_message(kek, "MAAA SEE😂")
        await raider.send_message(kek, "TERI ASLII")
        await raider.send_message(kek, "BAAAP")
        await raider.send_message(kek, "MAIN HI HUINN")
        await raider.send_message(kek, "MERAA NAJAYAZ🤣")
        await raider.send_message(kek, "BETA HAI TUU @sabkabapHACKERPROS")
        await raider.send_message(kek, "GUYS ADITYA JAYESH AAJ SE PAPA BULAAYEGAA. MUJHE 😂😂😂😂  ")
        await raider.send_message(kek, "ADITYA JAYESH KI MAA KI CHUDAAI HOOO RHI HAI  😂❌😂❌💦🍆💦🍌S" 
        await raider.send_message(kek, "ADITYA JAYESH KI MAA RANDI HAI SASTI WALI ")
        await raider.send_message(kek, "ADITYA TERIIIIII MAA RANDI ")
        await raider.send_message(kek, "MAAA KIIII CHOOTT MAARRUUU")
        await raider.send_message(kek, "TERI MAA SASTI RANDI ")
        await raider.send_message(kek, "TU MADERRCHODD HAI ")
        await raider.send_message(kek, "TERI.  BEHENN KEE GAND ME  LODEEE ")
        await raider.send_message(kek, "TERIII MAAA")
        await raider.send_message(kek, "KOO AISAA CHODAAA ")
        await raider.send_message(kek, "MADEERCHODD")
        await raider.send_message(kek, "KAALAAP GYII ")
        await raider.send_message(kek, "TERII MAAA KI CHOOT PHAAR DIYEE.   ADITYA JAYESH RANDI")
        await raider.send_message(kek, "TERAA ")
        await raider.send_message(kek, "KHANDAANN KO")
        await raider.send_message(kek, "ANDARRRR TKK ")
        await raider.send_message(kek, "CHOD DALAAA")
        await raider.send_message(kek, "TERIIII")
        await raider.send_message(kek, "BEHENNN ")
        await raider.send_message(kek, "ABHII MEREESEEE")
        await raider.send_message(kek, "ADITYA JAYESH KI  MAA MERE LUND PE ")
        await raider.send_message(kek, "BETAA TERI MAA CHUDD RHI HAIII ")
        await raider.send_message(kek, "ADITYA JAYESH KI MAA CHUD GYI")
        await raider.send_message(kek, "ADITYA JAYESH KI MAAA SASTI RANDI  @sabkabapHACKERPROS ")
        await raider.send_message(kek, "ADITYA JAYESH KI MAA KE CHUTT  @sabkabapHACKERPROS ")
        await raider.send_message(kek, "HATHII KAA")
        await raider.send_message(kek, "LAUDAA ")
        await raider.send_message(kek, "GHUSAA DIYAA")
        await raider.send_message(kek, "MADEERRCHODDD TERI MAA KI GAND KAAT LUNGAA   @sabkabapHACKERPROS ")
        await raider.send_message(kek, "ADITYA JAYESH. KI  MAA  @sabkabapHACKERPROS  ")
        await raider.send_message(kek, "ADITYA JAYESH ")
        await raider.send_message(kek, " RANDI. KAA.  PILLAAA HAI ")
        await raider.send_message(kek, "BEHENCHODDD")
        await raider.send_message(kek, "TERIII")
        await raider.send_message(kek, "BEHENN 🍑🍑💦")
        await raider.send_message(kek, "KII   ")
        await raider.send_message(kek, "CHUTTT ")
        await raider.send_message(kek, "MEEE")
        await raider.send_message(kek, "TOWERRR")
        await raider.send_message(kek, "GHUSAA DIYAA")
        await raider.send_message(kek, "ADITYA JAYESH KI. BEHAN KI CHOOTTT.  MERE.  LUND PE HAI 😂💦💦💦🍆🍆🍆🍆🍆")
        await raider.send_message(kek, "BETA ADITYA JAYESH TERAAA BAAP HU💥💥🔥🔥  ")
        await raider.send_message(kek, "SUNO GUYS MAI ADITYA JAYESH KAA BAAAP HU.🔥💥💥💦💦")
         await raider.send_message(kek,"ADI KAA BAAP SID OP 💥🔥 ")
          await raider.send_message(kek,"JOR SE BOLO ADI KI MA VERIFIED RANDI HAHAHHAHAHAHAHAHH💥💥🔥💥💥")
           await raider.send_message(kek,"OYE  BETA SUN TERI MAA KI CHOOTT CHODUNGAA OYO MEE 🍑💦🍑💦🍑💦🍌")
           